### ISSUE TITLE
Following the instruction It seems I'm running into this path not defined error

### ISSUE THREAD

**Issue by markpnoi26** [jchen1/eslint-plugin-absolute-imports#1]
```
module.exports = {
  root: true,
  parser: '@babel/eslint-parser',
  parserOptions: {
    ecmaVersion: 2020,
    requireConfigFile: false,
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true,
    },
    babelOptions: {
      presets: ['@babel/preset-react'],
    },
  },
  settings: {
    react: {
      version: 'detect',
    },
  },
  extends: [
    'eslint:recommended',
    'plugin:react/recommended',
    'plugin:jsx-a11y/recommended',
    'plugin:prettier/recommended',
    'plugin:react-hooks/recommended',
  ],
  overrides: [
    {
      files: ['**/*.test.js'],
      extends: ['plugin:jest/recommended', 'plugin:jest/style'],
    },
  ],
  env: {
    es6: true,
    browser: true,
    amd: true,
    node: true,
    jasmine: true,
  },
  rules: {
    'prettier/prettier': ['error', {}, { usePrettierrc: true }],
    'react/react-in-jsx-scope': 'off',
    'absolute-imports/only-absolute-imports': 1,
    'no-restricted-imports': [
      'warn',
      {
        'patterns': ['.*'],
      },
    ],
    /** To turn on as needed while fixing proper channels are in place */
    'react/prop-types': 'off',
    'react/no-find-dom-node': 'off',
    'react/no-unescaped-entities': 'off',
    'react/no-string-refs': 'off',
    'jsx-a11y/no-noninteractive-element-interactions': 'off',
    'jsx-a11y/click-events-have-key-events': 'off',
    'jsx-a11y/no-static-element-interactions': 'off',
    'jsx-a11y/no-autofocus': 'off',
    /** plugin import rule */
    'import/order': [
      'error',
      {
        groups: ['builtin', 'external', 'internal', ['parent', 'sibling']],
        pathGroups: [
          {
            pattern: 'react+(|-**)',
            group: 'external',
            position: 'before',
          },
          {
            pattern: 'history.js',
            group: 'external',
            position: 'after',
          },
          ...[
            /** Add main directory in src here
             * so external libraries get imported first
             * keep alphabetical please!
             */
            'api',
            'assets',
            'components',
            'configs',
            'pages',
            'lauouts',
            'redux',
            'resourceManager',
            'utility',
            '@**',
          ].map((dir) => ({
            pattern: dir + '/**',
            group: 'external',
            position: 'after',
          })),
        ],
        pathGroupsExcludedImportTypes: ['react'],
        alphabetize: {
          order: 'asc',
          caseInsensitive: true,
        },
      },
    ],
  },
  plugins: ['import', 'eslint-plugin-absolute-imports'],
};
```
```
ReferenceError: Error while loading rule 'absolute-imports/only-absolute-imports': path is not defined
Occurred while linting /Users/user/code/iserv/iservice-front/.eslintrc.js
    at findDirWithFile (/Users/user/code/iserv/iservice-front/node_modules/eslint-plugin-absolute-imports/index.js:17:13)
    at Object.create (/Users/user/code/iserv/iservice-front/node_modules/eslint-plugin-absolute-imports/index.js:58:23)
    at createRuleListeners (/Users/user/code/iserv/iservice-front/node_modules/eslint/lib/linter/linter.js:922:21)
    at /Users/user/code/iserv/iservice-front/node_modules/eslint/lib/linter/linter.js:1104:31
    at Array.forEach (<anonymous>)
    at runRules (/Users/user/code/iserv/iservice-front/node_modules/eslint/lib/linter/linter.js:1041:34)
    at Linter._verifyWithoutProcessors (/Users/user/code/iserv/iservice-front/node_modules/eslint/lib/linter/linter.js:1389:31)
    at Linter._verifyWithConfigArray (/Users/user/code/iserv/iservice-front/node_modules/eslint/lib/linter/linter.js:1729:21)
    at Linter.verify (/Users/user/code/iserv/iservice-front/node_modules/eslint/lib/linter/linter.js:1471:65)
    at Linter.verifyAndFix (/Users/user/code/iserv/iservice-front/node_modules/eslint/lib/linter/linter.js:1953:29)
```
ESLint version: 8.10.0
any insights on how to fix this would be fantastic. Thank you :)

**Comment by markpnoi26** [comment]
I was able to fix by requiring `path` and fixing line 8 in `index.js` to `var step of path.split(".")`
